/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hosbitaltest;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moamen.n
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
     Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Manager() {
        initComponents();
        Patient_Table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD , 14));
        Patient_Table.getTableHeader().setOpaque(false);
        Patient_Table.getTableHeader().setBackground(new Color (255,255,255));
        Doctor_Table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD , 14));
        Doctor_Table.getTableHeader().setOpaque(false);
        Doctor_Table.getTableHeader().setBackground(new Color (255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Doctor_Table = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Patient_Table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        AddNewUser = new javax.swing.JButton();
        EDTDOC = new javax.swing.JButton();
        View_doc = new javax.swing.JButton();
        Search_P_id = new javax.swing.JButton();
        Search_P_name = new javax.swing.JButton();
        btnDOCNAME = new javax.swing.JButton();
        btnDOCID = new javax.swing.JButton();
        srcdID = new javax.swing.JTextField();
        srcdname = new javax.swing.JTextField();
        srcpNAME = new javax.swing.JTextField();
        srhpID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(146, 233, 251));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Manager", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        Doctor_Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Doctor_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Doctor_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor ID", "Doctor Name", "Specialization", "Tel."
            }
        ));
        Doctor_Table.setShowGrid(true);
        jScrollPane2.setViewportView(Doctor_Table);

        Patient_Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Patient_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Patient_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Age", "Tel."
            }
        ));
        Patient_Table.setShowGrid(true);
        jScrollPane1.setViewportView(Patient_Table);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        AddNewUser.setBackground(new java.awt.Color(0, 102, 102));
        AddNewUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddNewUser.setForeground(new java.awt.Color(255, 255, 255));
        AddNewUser.setText("Add New User");
        AddNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewUserActionPerformed(evt);
            }
        });

        EDTDOC.setBackground(new java.awt.Color(0, 102, 102));
        EDTDOC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EDTDOC.setForeground(new java.awt.Color(255, 255, 255));
        EDTDOC.setText("EDIT DOCTORS");
        EDTDOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDTDOCActionPerformed(evt);
            }
        });

        View_doc.setBackground(new java.awt.Color(0, 102, 102));
        View_doc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View_doc.setForeground(new java.awt.Color(255, 255, 255));
        View_doc.setText("VIEW DOCTORS");
        View_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_docActionPerformed(evt);
            }
        });

        Search_P_id.setBackground(new java.awt.Color(0, 102, 102));
        Search_P_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search_P_id.setForeground(new java.awt.Color(255, 255, 255));
        Search_P_id.setText("SEARCH FOR A PATIENT BY ID");
        Search_P_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_P_idActionPerformed(evt);
            }
        });

        Search_P_name.setBackground(new java.awt.Color(0, 102, 102));
        Search_P_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search_P_name.setForeground(new java.awt.Color(255, 255, 255));
        Search_P_name.setText("SEARCH FOR A PATIENT BY NAME");
        Search_P_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_P_nameActionPerformed(evt);
            }
        });

        btnDOCNAME.setBackground(new java.awt.Color(0, 102, 102));
        btnDOCNAME.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDOCNAME.setForeground(new java.awt.Color(255, 255, 255));
        btnDOCNAME.setText("SEARCH FOR A DOCTOR BY NAME");
        btnDOCNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOCNAMEActionPerformed(evt);
            }
        });

        btnDOCID.setBackground(new java.awt.Color(0, 102, 102));
        btnDOCID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDOCID.setForeground(new java.awt.Color(255, 255, 255));
        btnDOCID.setText("SEARCH FOR A DOCTOR BY ID");
        btnDOCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOCIDActionPerformed(evt);
            }
        });

        srcdID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        srcdID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        srcdname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        srcdname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        srcdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcdnameActionPerformed(evt);
            }
        });

        srcpNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        srcpNAME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        srhpID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        srhpID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        srhpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srhpIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDOCNAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDOCID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View_doc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Search_P_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Search_P_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddNewUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EDTDOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srcdname, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(srcdID)
                    .addComponent(srcpNAME)
                    .addComponent(srhpID))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(AddNewUser)
                .addGap(25, 25, 25)
                .addComponent(EDTDOC)
                .addGap(25, 25, 25)
                .addComponent(View_doc)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_P_id)
                    .addComponent(srhpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_P_name)
                    .addComponent(srcpNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDOCNAME)
                    .addComponent(srcdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDOCID)
                    .addComponent(srcdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EDTDOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDTDOCActionPerformed
         dispose();
         new Doctoradd().setVisible(true);
    }//GEN-LAST:event_EDTDOCActionPerformed

    private void View_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_docActionPerformed
       //to clear table before search
        DefaultTableModel model = (DefaultTableModel) Doctor_Table.getModel();
        model.setRowCount(0);
        
        try{ String sql="select * from APP.DOCTOR";
            con=connect.connectdb();
            pst=con.prepareStatement(sql);
            rs= pst.executeQuery();
            //jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            while(rs.next()){
                String DoctorID=String.valueOf(rs.getInt("ID"));
                String DoctorName=String.valueOf(rs.getString("NAME"));
                String docage=String.valueOf(rs.getString("SPECIALIZATION"));
                String docTel=String.valueOf(rs.getInt("TEL"));
                
                String tbdata[]={DoctorID,DoctorName,docage,docTel};
                DefaultTableModel tblmodel=(DefaultTableModel)Doctor_Table.getModel();
                tblmodel.addRow(tbdata);
            }
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }         
    }//GEN-LAST:event_View_docActionPerformed

    private void Search_P_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_P_idActionPerformed
         DefaultTableModel model = (DefaultTableModel) Patient_Table.getModel();
        model.setRowCount(0);
        con=connect.connectdb();
        if (srhpID.getText().equals("")) {
            JOptionPane.showMessageDialog( this, "Please enter PATIENT ID","Error", JOptionPane.ERROR_MESSAGE);
            return;}
        int idd=Integer.parseInt(srhpID.getText());
        PATINT P=new PATINT();
        DefaultTableModel tblmodel=(DefaultTableModel)Patient_Table.getModel();
        tblmodel.addRow(P.Search_id(idd));

    }//GEN-LAST:event_Search_P_idActionPerformed

    private void Search_P_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_P_nameActionPerformed
        //to clear table before search
        DefaultTableModel model = (DefaultTableModel) Patient_Table.getModel();
        model.setRowCount(0);
       
            con=connect.connectdb();
            if (srcpNAME.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter patient name","Error", JOptionPane.ERROR_MESSAGE);
                return;}
            String name=srcpNAME.getText();
            PATINT P=new PATINT();
            DefaultTableModel tblmodel=(DefaultTableModel)Patient_Table.getModel();
            tblmodel.addRow(P.Search_name(name));

    }//GEN-LAST:event_Search_P_nameActionPerformed

    private void btnDOCNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOCNAMEActionPerformed
        
        //to clear table before search
        DefaultTableModel model = (DefaultTableModel) Doctor_Table.getModel();
        model.setRowCount(0);

            if (srcdname.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Doctor name","Error", JOptionPane.ERROR_MESSAGE);
                return;}
            String name=srcdname.getText();
            Maindoctor d=new Maindoctor();
            DefaultTableModel tblmodel=(DefaultTableModel)Doctor_Table.getModel();
            tblmodel.addRow(d.Search_name(name));
            
            

    }//GEN-LAST:event_btnDOCNAMEActionPerformed

    private void btnDOCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOCIDActionPerformed
         //to clear table before search
        DefaultTableModel model = (DefaultTableModel) Doctor_Table.getModel();
        model.setRowCount(0);
            if (srcdID.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Doctor ID","Error", JOptionPane.ERROR_MESSAGE);
                return;}
            String id=srcdID.getText();
            Maindoctor d=new Maindoctor();
            DefaultTableModel tblmodel=(DefaultTableModel)Doctor_Table.getModel();
            tblmodel.addRow(d.Search_id(id));
    }//GEN-LAST:event_btnDOCIDActionPerformed

    private void srhpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srhpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srhpIDActionPerformed

    private void srcdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcdnameActionPerformed

    private void AddNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewUserActionPerformed
        
        new Registeration().setVisible(true);
    }//GEN-LAST:event_AddNewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewUser;
    private javax.swing.JTable Doctor_Table;
    private javax.swing.JButton EDTDOC;
    private javax.swing.JTable Patient_Table;
    private javax.swing.JButton Search_P_id;
    private javax.swing.JButton Search_P_name;
    private javax.swing.JButton View_doc;
    private javax.swing.JButton btnDOCID;
    private javax.swing.JButton btnDOCNAME;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField srcdID;
    private javax.swing.JTextField srcdname;
    private javax.swing.JTextField srcpNAME;
    private javax.swing.JTextField srhpID;
    // End of variables declaration//GEN-END:variables
}
