/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hosbitaltest;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Helal
 */
public class Reception extends javax.swing.JFrame  {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    
    /**
     * Creates new form Reception
     */
    public Reception() {
        initComponents();
        Patient_Table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD , 14));
        Patient_Table.getTableHeader().setOpaque(false);
        Patient_Table.getTableHeader().setBackground(new Color (255,255,255));
        Doctor_Table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD , 14));
        Doctor_Table.getTableHeader().setOpaque(false);
        Doctor_Table.getTableHeader().setBackground(new Color (255,255,255));
        //getdata();
    }
    /*
private void getdata()
{
     String sql="select ID as 'Patient ID',NAME as 'Patient Name',AGE as 'AGE',TEL as 'TEL' from APP.PATIENT order by ID";
        try{
            con=connect.connectdb();
            pst=con.prepareStatement(sql);
            rs= pst.executeQuery();
            Patient_Table.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         
}*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Doctor_Table = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Patient_Table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Set_Appointment = new javax.swing.JButton();
        btnDOCID = new javax.swing.JButton();
        srcdID = new javax.swing.JTextField();
        srcdname = new javax.swing.JTextField();
        srcpNAME = new javax.swing.JTextField();
        btnDOCNAME = new javax.swing.JButton();
        Search_P_name = new javax.swing.JButton();
        Search_P_id = new javax.swing.JButton();
        View_doc = new javax.swing.JButton();
        PATIENTSD = new javax.swing.JButton();
        View_P = new javax.swing.JButton();
        srhpID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(146, 233, 251));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Receptionist", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        Doctor_Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Doctor_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor ID", "Doctor Name", "Specialization", "Tel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Doctor_Table.setRowHeight(20);
        Doctor_Table.setShowGrid(true);
        jScrollPane2.setViewportView(Doctor_Table);

        Patient_Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Patient_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Age", "Tel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Patient_Table.setRowHeight(20);
        Patient_Table.setShowGrid(true);
        jScrollPane1.setViewportView(Patient_Table);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Set_Appointment.setBackground(new java.awt.Color(0, 102, 102));
        Set_Appointment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Set_Appointment.setForeground(new java.awt.Color(255, 255, 255));
        Set_Appointment.setText("SET APPOINTMENT");
        Set_Appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Set_AppointmentActionPerformed(evt);
            }
        });

        btnDOCID.setBackground(new java.awt.Color(0, 102, 102));
        btnDOCID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDOCID.setForeground(new java.awt.Color(255, 255, 255));
        btnDOCID.setText("SEARCH FOR A DOCTOR BY ID");
        btnDOCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOCIDActionPerformed(evt);
            }
        });

        srcdID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        srcdID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        srcdname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        srcdname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        srcdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcdnameActionPerformed(evt);
            }
        });

        srcpNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        srcpNAME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnDOCNAME.setBackground(new java.awt.Color(0, 102, 102));
        btnDOCNAME.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDOCNAME.setForeground(new java.awt.Color(255, 255, 255));
        btnDOCNAME.setText("SEARCH FOR DOCTOR BY NAME");
        btnDOCNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOCNAMEActionPerformed(evt);
            }
        });

        Search_P_name.setBackground(new java.awt.Color(0, 102, 102));
        Search_P_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search_P_name.setForeground(new java.awt.Color(255, 255, 255));
        Search_P_name.setText("SEARCH FOR PATIENT BY NAME");
        Search_P_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_P_nameActionPerformed(evt);
            }
        });

        Search_P_id.setBackground(new java.awt.Color(0, 102, 102));
        Search_P_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search_P_id.setForeground(new java.awt.Color(255, 255, 255));
        Search_P_id.setText("SEARCH FOR A PATIENT BY ID");
        Search_P_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_P_idActionPerformed(evt);
            }
        });

        View_doc.setBackground(new java.awt.Color(0, 102, 102));
        View_doc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View_doc.setForeground(new java.awt.Color(255, 255, 255));
        View_doc.setText("VIEW DOCTOR");
        View_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_docActionPerformed(evt);
            }
        });

        PATIENTSD.setBackground(new java.awt.Color(0, 102, 102));
        PATIENTSD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PATIENTSD.setForeground(new java.awt.Color(255, 255, 255));
        PATIENTSD.setText("EDIT PATIENTS ");
        PATIENTSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PATIENTSDActionPerformed(evt);
            }
        });

        View_P.setBackground(new java.awt.Color(0, 102, 102));
        View_P.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View_P.setForeground(new java.awt.Color(255, 255, 255));
        View_P.setText("VIEW PATIENT");
        View_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_PActionPerformed(evt);
            }
        });

        srhpID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        srhpID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Search_P_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(View_doc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(View_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PATIENTSD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Search_P_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(srcpNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(srhpID)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Set_Appointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDOCID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDOCNAME, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(srcdname))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(srcdID, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(PATIENTSD)
                .addGap(18, 18, 18)
                .addComponent(View_P)
                .addGap(18, 18, 18)
                .addComponent(View_doc)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_P_id)
                    .addComponent(srhpID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_P_name)
                    .addComponent(srcpNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDOCNAME)
                    .addComponent(srcdname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDOCID)
                    .addComponent(srcdID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Set_Appointment)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void View_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_PActionPerformed
      //to clear table before search
        DefaultTableModel model = (DefaultTableModel) Patient_Table.getModel();
        model.setRowCount(0);
        try{ String sql="select * from APP.PATIENT1";
            con=connect.connectdb();
            pst=con.prepareStatement(sql);
            rs= pst.executeQuery();
            //jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            while(rs.next()){
                String PatientID=String.valueOf(rs.getInt("ID"));
                String PatientName=String.valueOf(rs.getString("NAME"));
                String Patientage=String.valueOf(rs.getInt("AGE"));
                String PatientTel=String.valueOf(rs.getInt("TEL"));
                
                String tbdata[]={PatientID,PatientName,Patientage,PatientTel};
                DefaultTableModel tblmodel=(DefaultTableModel)Patient_Table.getModel();
                tblmodel.addRow(tbdata);
            }
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }       
 
        
    }//GEN-LAST:event_View_PActionPerformed

    private void View_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_docActionPerformed
     //to clear table before search
        DefaultTableModel model = (DefaultTableModel) Doctor_Table.getModel();
        model.setRowCount(0);
        
        try{ String sql="select * from APP.DOCTOR";
            con=connect.connectdb();
            pst=con.prepareStatement(sql);
            rs= pst.executeQuery();
            
            while(rs.next()){
                String DoctorID=String.valueOf(rs.getInt("ID"));
                String DoctorName=String.valueOf(rs.getString("NAME"));
                String docage=String.valueOf(rs.getString("SPECIALIZATION"));
                String docTel=String.valueOf(rs.getInt("TEL"));
                
                String tbdata[]={DoctorID,DoctorName,docage,docTel};
                DefaultTableModel tblmodel=(DefaultTableModel)Doctor_Table.getModel();
                tblmodel.addRow(tbdata);
            }
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }       
    }//GEN-LAST:event_View_docActionPerformed

    private void Search_P_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_P_idActionPerformed
       //to clear table before search
        DefaultTableModel model = (DefaultTableModel) Patient_Table.getModel();
        model.setRowCount(0);
        if (srhpID.getText().equals("")) {
            JOptionPane.showMessageDialog( this, "Please enter PATIENT ID","Error", JOptionPane.ERROR_MESSAGE);
            return;}
        int idd = 0;
        try{idd= Integer.parseInt(srhpID.getText());}
        catch (Exception e) {
        JOptionPane.showMessageDialog( this, "Your entry was invalid, please enter a number","Error", JOptionPane.ERROR_MESSAGE);}
        PATINT P=new PATINT();
        DefaultTableModel tblmodel=(DefaultTableModel)Patient_Table.getModel();
        tblmodel.addRow(P.Search_id(idd));

    }//GEN-LAST:event_Search_P_idActionPerformed

    private void Search_P_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_P_nameActionPerformed
     //to clear table before search
        DefaultTableModel model = (DefaultTableModel) Patient_Table.getModel();
        model.setRowCount(0);
       
            con=connect.connectdb();
            if (srcpNAME.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter patient name","Error", JOptionPane.ERROR_MESSAGE);
                return;}
            String name=srcpNAME.getText();
            PATINT P=new PATINT();
            DefaultTableModel tblmodel=(DefaultTableModel)Patient_Table.getModel();
            tblmodel.addRow(P.Search_name(name));
        
    }//GEN-LAST:event_Search_P_nameActionPerformed

    private void btnDOCNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOCNAMEActionPerformed
       //to clear table before search
        DefaultTableModel model = (DefaultTableModel) Doctor_Table.getModel();
        model.setRowCount(0);

            if (srcdname.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Doctor name","Error", JOptionPane.ERROR_MESSAGE);
                return;}
            String name=srcdname.getText();
            Maindoctor d=new Maindoctor();
            DefaultTableModel tblmodel=(DefaultTableModel)Doctor_Table.getModel();
            tblmodel.addRow(d.Search_name(name));
            
            
    }//GEN-LAST:event_btnDOCNAMEActionPerformed

    private void btnDOCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOCIDActionPerformed
       //to clear table before search
        DefaultTableModel model = (DefaultTableModel) Doctor_Table.getModel();
        model.setRowCount(0);
            if (srcdID.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Doctor ID","Error", JOptionPane.ERROR_MESSAGE);
                return;}
            String id=srcdID.getText();
            Maindoctor d=new Maindoctor();
            DefaultTableModel tblmodel=(DefaultTableModel)Doctor_Table.getModel();
            tblmodel.addRow(d.Search_id(id));
            
           
    }//GEN-LAST:event_btnDOCIDActionPerformed

    private void Set_AppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Set_AppointmentActionPerformed
        
         new Appointment().setVisible(true);
    }//GEN-LAST:event_Set_AppointmentActionPerformed

    private void PATIENTSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PATIENTSDActionPerformed
       
                        
                        new Patientedit().setVisible(true);
    }//GEN-LAST:event_PATIENTSDActionPerformed

    private void srcdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcdnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reception().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Doctor_Table;
    private javax.swing.JButton PATIENTSD;
    private javax.swing.JTable Patient_Table;
    private javax.swing.JButton Search_P_id;
    private javax.swing.JButton Search_P_name;
    private javax.swing.JButton Set_Appointment;
    private javax.swing.JButton View_P;
    private javax.swing.JButton View_doc;
    private javax.swing.JButton btnDOCID;
    private javax.swing.JButton btnDOCNAME;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField srcdID;
    private javax.swing.JTextField srcdname;
    private javax.swing.JTextField srcpNAME;
    private javax.swing.JTextField srhpID;
    // End of variables declaration//GEN-END:variables
}
